export const REGISTRATION_DATA_START = "REGISTRATION_DATA_START";
export const REGISTRATION_DATA_SUCCESS = "REGISTRATION_DATA_SUCCESS";
export const REGISTRATION_DATA_FAILURE = "REGISTRATION_DATA_FAILURE";

export const LOGIN_DATA_START = "LOGIN_DATA_START";
export const LOGIN_DATA_SUCCESS = "LOGIN_DATA_SUCCESS";
export const LOGIN_DATA_FAILURE = "LOGIN_DATA_FAILURE";
