export const REGISTRATION_DATA_START = "REGISTRATION_DATA_START";
export const REGISTRATION_DATA_SUCCESS = "REGISTRATION_DATA_SUCCESS";
export const REGISTRATION_DATA_FAILURE = "REGISTRATION_DATA_FAILURE";